
if(typeof CELL==='undefined')
var CELL={};CELL.method=function(that,name,method,_super){if(_super){var m=that[name];_super[name]=function(){if(typeof m!=='function')
throw new Error('_super.'+name+'() is not a function');return m.apply(that,arguments);};}
that[name]=method;};CELL.getter=function(that,name,obj,prop){var getter=function(){return obj[prop];};that[name]=getter;};CELL.setter=function(that,name,obj,prop){var setter=function(arg){obj[prop]=arg;return that;};that['set'+name.substring(0,1).toUpperCase()+name.substring(1)]=setter;};CELL.responds=function(that,name){return(that[name]&&typeof that[name]==='function');};CELL.log=function(){if(console&&typeof console.log==='function')
return console.log.apply(console,arguments);};CELL.remove=function(that,e){"use strict";if(that===void 0||that===null||!Array.isArray(that))
throw new TypeError();for(var i=that.length-1;i>=0;i--)
if(e===that[i])that.splice(i,1);};CELL.unique=function(that){"use strict";if(that===void 0||that===null||!Array.isArray(that))
throw new TypeError();var a=that.concat();for(var i=0;i<a.length;i++){for(var j=i+1;j<a.length;j++){if(a[i]===a[j]){a.splice(j,1);j--;}}}
return a;};if(!Array.prototype.indexOf){Array.prototype.indexOf=function(searchElement){"use strict";if(this==null){throw new TypeError();}
var t=Object(this);var len=t.length>>>0;if(len===0){return-1;}
var n=0;if(arguments.length>0){n=Number(arguments[1]);if(n!=n){n=0;}else if(n!=0&&n!=Infinity&&n!=-Infinity){n=(n>0||-1)*Math.floor(Math.abs(n));}}
if(n>=len){return-1;}
var k=n>=0?n:Math.max(len-Math.abs(n),0);for(;k<len;k++){if(k in t&&t[k]===searchElement){return k;}}
return-1;}}
CELL.DEBUG=false;CELL.debug=function(){if(CELL.DEBUG&&console&&typeof console.log==='function')
return console.log.apply(console,arguments);};if(typeof CELL==='undefined')
var CELL={};CELL.emitter=function(spec,my){my=my||{};var _super={};my.handlers={};var on;var emit;var off;var that={};on=function(type,handler){if(typeof handler==='function'){my.handlers[type]=my.handlers[type]||[];my.handlers[type].push(handler);}
else{throw new Error('emitter: not a function');}};emit=function(){var args=Array.prototype.slice.call(arguments);var name=args.shift();if(my.handlers[name]){for(var i=0;i<my.handlers[name].length;i++){if(my.handlers[name][i])
my.handlers[name][i].apply(this,args);}}
if(my.handlers['*']){args.unshift(name);for(var i=0;i<my.handlers['*'].length;i++){if(my.handlers['*'][i])
my.handlers['*'][i].apply(this,args);}}};off=function(type,handler){if(my.handlers[type]){for(var i=my.handlers[type].length-1;i>=0;i--){if(handler===my.handlers[type][i]){my.handlers[type].splice(i,1);}}}};CELL.method(that,'on',on,_super);CELL.method(that,'emit',emit,_super);CELL.method(that,'off',off,_super);CELL.getter(that,'handlers',my,'handlers');return that;};if(typeof CELL==='undefined')
var CELL={};CELL.container=function(spec,my){var _super={};my=my||{};my.name=spec.name||'';my.children=my.children||{};my.json=my.json||{};var find;var load;var refresh;var that=CELL.emitter({});refresh=function(){for(var c in my.children){if(my.children.hasOwnProperty(c)&&typeof my.json[c]!=='undefined')
my.children[c].refresh(my.json[c]);}};find=function(path){path=path.replace(/^\/+/,'');var comps=path.split('/');var next=comps.shift();if(next.length>0)
return my.children[next].find(comps.join('/'));else
return that;};load=function(){throw new Error('`load` must be implemented : '+my.path);};CELL.method(that,'load',load,_super);CELL.method(that,'refresh',refresh,_super);CELL.method(that,'find',find,_super);CELL.getter(that,'children',my,'children');CELL.getter(that,'name',my,'name');CELL.getter(that,'json',my,'json');return that;};if(typeof CELL==='undefined')
var CELL={};CELL.cell=function(spec,my){var _super={};my=my||{};my.path=spec.path||'/';my.container=spec.container;my.children=my.children||{};my.json=my.json||{};my.element=null;var build;var refresh;var find;var bind;var that=CELL.emitter({},my);build=function(){throw new Error('`build` must be implemented : '+my.path);my.element=$('<div></div>');my.children['foo']=foo_c({path:my.path+'/foo',container:my.container});my.element.append(my.children['foo'].build());return my.element;};bind=function(){my.hdlr=my.hdlr||function(){var args=Array.prototype.slice.call(arguments);that['emit'].apply(this,args);};for(var c in my.children){if(my.children.hasOwnProperty(c)){my.children[c].off('*',my.hdlr);my.children[c].on('*',my.hdlr);}}};refresh=function(json){my.json=json;for(var c in my.children){if(my.children.hasOwnProperty(c)&&typeof my.json[c]!=='undefined')
my.children[c].refresh(my.json[c]);}
bind();};find=function(path){path=path.replace(/^\/+/,'');var comps=path.split('/');var next=comps.shift();if(next.length>0)
return my.children[next].find(comps.join('/'));else
return that;};CELL.method(that,'build',build,_super);CELL.method(that,'refresh',refresh,_super);CELL.method(that,'find',find,_super);CELL.method(that,'bind',bind,_super);CELL.getter(that,'children',my,'children');CELL.getter(that,'element',my,'element');CELL.getter(that,'path',my,'path');CELL.getter(that,'json',my,'json');return that;};var TL=TL||{};(function(window,document,version,callback){var j,d;var loaded=false;if(!(j=window.jQuery)||version>j.fn.jquery||callback(j,loaded)){var script=document.createElement('script');script.type='text/javascript';script.src='http://ajax.googleapis.com/ajax/libs/jquery/1.7.2/jquery.min.js';script.onload=script.onreadystatechange=function(){if(!loaded&&(!(d=this.readyState)||d=='loaded'||d=='complete')){callback((j=window.jQuery).noConflict(1),loaded=true);j(script).remove();}};document.documentElement.childNodes[0].appendChild(script);}})(window,document,'1.7',function($,jquery_loaded){$.extend($.easing,{linear:function(x,t,b,c,d){return b+c*t/d;},easeInQuad:function(x,t,b,c,d){return c*(t/=d)*t+b;},easeOutQuad:function(x,t,b,c,d){return-c*(t/=d)*(t-2)+b;},easeInOutQuad:function(x,t,b,c,d){if((t/=d/2)<1)return c/2*t*t+b;return-c/2*((--t)*(t-2)-1)+b;},easeInCubic:function(x,t,b,c,d){return c*(t/=d)*t*t+b;},easeOutCubic:function(x,t,b,c,d){return c*((t=t/d-1)*t*t+1)+b;},easeInOutCubic:function(x,t,b,c,d){if((t/=d/2)<1)return c/2*t*t*t+b;return c/2*((t-=2)*t*t+2)+b;},easeInQuart:function(x,t,b,c,d){return c*(t/=d)*t*t*t+b;},easeOutQuart:function(x,t,b,c,d){return-c*((t=t/d-1)*t*t*t-1)+b;},easeInOutQuart:function(x,t,b,c,d){if((t/=d/2)<1)return c/2*t*t*t*t+b;return-c/2*((t-=2)*t*t*t-2)+b;},easeInQuint:function(x,t,b,c,d){return c*(t/=d)*t*t*t*t+b;},easeOutQuint:function(x,t,b,c,d){return c*((t=t/d-1)*t*t*t*t+1)+b;},easeInOutQuint:function(x,t,b,c,d){if((t/=d/2)<1)return c/2*t*t*t*t*t+b;return c/2*((t-=2)*t*t*t*t+2)+b;},easeInSine:function(x,t,b,c,d){return-c*Math.cos(t/d*(Math.PI/2))+c+b;},easeOutSine:function(x,t,b,c,d){return c*Math.sin(t/d*(Math.PI/2))+b;},easeInOutSine:function(x,t,b,c,d){return-c/2*(Math.cos(Math.PI*t/d)-1)+b;},easeInExpo:function(x,t,b,c,d){return(t==0)?b:c*Math.pow(2,10*(t/d-1))+b;},easeOutExpo:function(x,t,b,c,d){return(t==d)?b+c:c*(-Math.pow(2,-10*t/d)+1)+b;},easeInOutExpo:function(x,t,b,c,d){if(t==0)return b;if(t==d)return b+c;if((t/=d/2)<1)return c/2*Math.pow(2,10*(t-1))+b;return c/2*(-Math.pow(2,-10*--t)+2)+b;},easeInCirc:function(x,t,b,c,d){return-c*(Math.sqrt(1-(t/=d)*t)-1)+b;},easeOutCirc:function(x,t,b,c,d){return c*Math.sqrt(1-(t=t/d-1)*t)+b;},easeInOutCirc:function(x,t,b,c,d){if((t/=d/2)<1)return-c/2*(Math.sqrt(1-t*t)-1)+b;return c/2*(Math.sqrt(1-(t-=2)*t)+1)+b;},easeInElastic:function(x,t,b,c,d){var s=1.70158;var p=0;var a=c;if(t==0)return b;if((t/=d)==1)return b+c;if(!p)p=d*.3;if(a<Math.abs(c)){a=c;var s=p/4;}
else var s=p/(2*Math.PI)*Math.asin(c/a);return-(a*Math.pow(2,10*(t-=1))*Math.sin((t*d-s)*(2*Math.PI)/p))+b;},easeOutElastic:function(x,t,b,c,d){var s=1.70158;var p=0;var a=c;if(t==0)return b;if((t/=d)==1)return b+c;if(!p)p=d*.3;if(a<Math.abs(c)){a=c;var s=p/4;}
else var s=p/(2*Math.PI)*Math.asin(c/a);return a*Math.pow(2,-10*t)*Math.sin((t*d-s)*(2*Math.PI)/p)+c+b;},easeInOutElastic:function(x,t,b,c,d){var s=1.70158,p=0,a=c;if(t==0)return b;if((t/=d/2)==2)return b+c;if(!p)p=d*(.3*1.5);if(a<Math.abs(c)){a=c;var s=p/4;}
else var s=p/(2*Math.PI)*Math.asin(c/a);if(t<1)return-.5*(a*Math.pow(2,10*(t-=1))*Math.sin((t*d-s)*(2*Math.PI)/p))+b;return a*Math.pow(2,-10*(t-=1))*Math.sin((t*d-s)*(2*Math.PI)/p)*.5+c+b;},easeInBack:function(x,t,b,c,d,s){if(s==undefined)s=1.70158;return c*(t/=d)*t*((s+1)*t-s)+b;},easeOutBack:function(x,t,b,c,d,s){if(s==undefined)s=1.70158;return c*((t=t/d-1)*t*((s+1)*t+s)+1)+b;},easeInOutBack:function(x,t,b,c,d,s){if(s==undefined)s=1.70158;if((t/=d/2)<1)return c/2*(t*t*(((s*=(1.525))+1)*t-s))+b;return c/2*((t-=2)*t*(((s*=(1.525))+1)*t+s)+2)+b;},easeInBounce:function(x,t,b,c,d){return c-$.easing.easeOutBounce(x,d-t,0,c,d)+b;},easeOutBounce:function(x,t,b,c,d){if((t/=d)<(1/2.75)){return c*(7.5625*t*t)+b;}else if(t<(2/2.75)){return c*(7.5625*(t-=(1.5/2.75))*t+.75)+b;}else if(t<(2.5/2.75)){return c*(7.5625*(t-=(2.25/2.75))*t+.9375)+b;}else{return c*(7.5625*(t-=(2.625/2.75))*t+.984375)+b;}},easeInOutBounce:function(x,t,b,c,d){if(t<d/2)return $.easing.easeInBounce(x,t*2,0,c,d)*.5+b;return $.easing.easeOutBounce(x,t*2-d,0,c,d)*.5+c*.5+b;}});TL.waits=TL.waits||[];TL.isIE=(/MSIE (\d+\.\d+);/.test(navigator.userAgent));TL.build=function(spec){return TL.core_ct($,spec);};for(var i=0;i<TL.waits.length;i++){TL.waits[i].core_ready();}
delete TL.waits;});var TL=TL||{};TL.waits=TL.waits||[];TL.plugin=function(spec,my){var _super={};my=my||{};my.core=null;my.init_cb=null;my._preview=spec._preview||false;var init;var on;var stop;var call;var core_ready;var that={};core_ready=function(){init(my.init_cb);};on=function(type,hdlr){my.core.on(type,hdlr);};stop=function(){my.core.stop();};init=function(cb){my.init_cb=cb;if(TL.build){my.core=TL.build(spec);my.core.init(function($){my.init_cb(that,$);});if(my._preview){my.init_cb(that,$);}}else{TL.waits.push(that);}
return that;};call=function(){var args=Array.prototype.slice.call(arguments);my.core.call.apply(this,args);};CELL.method(that,'init',init,_super);CELL.method(that,'on',on,_super);CELL.method(that,'stop',stop,_super);CELL.method(that,'core_ready',core_ready,_super);CELL.method(that,'call',call,_super);return that;};var TL=TL||{waits:[]};TL.core_ct=function($,spec,my){var _super={};my=my||{};my.lyts={};my.ENDPOINT_URL='http://capsules.teleportd.com/capsule/';my.REFRESH_PERIOD=5000;my._preview=spec._preview||false;my.capsule_id=spec.capsule_id;my.element_id=spec.element_id;my.width=spec.width||400;my.height=spec.height||400;var lyt;var load;var refresh;var init;var call;var brand;var update;var inject;var data;var that=CELL.container({name:'core'},my);lyt=function(lyt){if(!my.lyts[lyt]){my.lyts[lyt]=TL[lyt+'_c']($,{path:'/'+lyt,container:that});my.lyts[lyt].build();}
return my.lyts[lyt];};handle_radius=function(pln){if(pln==='free'){my.element.find('.teleportd-glass').css({'-webkit-border-radius':'4px 4px 0 0','-moz-border-radius':'4px 4px 0 0','border-radius':'4px 4px 0 0'});}else{my.element.find('.teleportd-glass').css({'-webkit-border-radius':'4px','-moz-border-radius':'4px','border-radius':'4px'});}};brand=function(){var height=my.height;if(my.pln==='free'){my.element.find('.teleportd-glass').css({'padding-top':'1px','-webkit-border-radius':'4px 4px 0 0','-moz-border-radius':'4px 4px 0 0','border-radius':'4px 4px 0 0'});my.element.find('.teleportd-plugin-bottom').css('display','block');height=height-36;}else{my.element.find('.teleportd-glass').css({'padding-top':'0','-webkit-border-radius':'4px','-moz-border-radius':'4px','border-radius':'4px'});my.element.find('.teleportd-plugin-bottom').css('display','none');}
return height;};load=function(){my.width=(my.width%2===0)?my.width:my.width-1;my.height=(my.height%2===0)?my.height:my.height-1;my.element=$('#'+my.element_id);my.element.addClass('teleportd-plugin').css({'width':my.width,'height':my.height});my.element.append($('<div/>').addClass('teleportd-plugin-top'));my.element.append($('<div/>').addClass('teleportd-glass'));my.element.append($('<div/>').addClass('teleportd-plugin-bottom').append($('<a/>').addClass('teleportd-plugin-link').attr('href','http://teleportd.com/').attr('target','_blank')));TL.isIE&&my.element.addClass('ie');};refresh=function(){var lyt_height=brand();my.element.find('.teleportd-layout').remove();my.element.find('.teleportd-glass').css({'width':my.width,'height':lyt_height});my.element.find('.teleportd-plugin-bottom').css('top',lyt_height);my.json={};my.json[my.plg.layout]={pln:my.pln,plg:my.plg,pics:my.pics,width:my.width,height:lyt_height};my.children[my.plg.layout]=lyt(my.plg.layout);$(my.children[my.plg.layout].element()).insertAfter(my.element.find('.teleportd-plugin-top'));handle_radius(my.pln);_super.refresh();};init=function(cb){that.load();if(!my._preview){update(function(err){if(err){}else{that.refresh();if(!my._preview){cb($);}}});}};call=function(){var args=Array.prototype.slice.call(arguments);var method=args.shift();if(my._preview&&method==='inject'){inject.apply(that,args);}
if(method==='data'){data.apply(that,args);}
if(my.plg&&my.children[my.plg.layout]&&typeof my.children[my.plg.layout].call==='function'){args.unshift(method);my.children[my.plg.layout].call(args);}};update=function(cb){var endpoint=my.ENDPOINT_URL+my.capsule_id+'?callback=?';$.getJSON(endpoint,function(data){my.data=data;if(data.ok){my.pln=data.capsule.pln;my.plg={layout:data.capsule.plg.layout,caption_display:data.capsule.plg.caption_display};my.pics=data.capsule.pic;cb();}else{cb(data.error);}});};inject=function(json){if(my._preview&&json.ok){my.pln=json.capsule.pln;my.plg=json.capsule.plg;my.pics=json.capsule.pic;that.refresh();}};data=function(cb){if(typeof cb==='function'&&my.data.ok){cb(my.data);}};CELL.method(that,'lyt',lyt,_super);CELL.method(that,'load',load,_super);CELL.method(that,'refresh',refresh,_super);CELL.method(that,'init',init,_super);CELL.method(that,'call',call,_super);return that;};var TL=TL||{waits:[]};TL.carousel_c=function($,spec,my){var _super={};my=my||{};my.pics={};my.thumbs={};my.index=0;my.thumbs_width=30;my.thumbs_outer_width=44;var pic;var thumb;var keep_index;var handle_radius;var click_to_slide;var bind_arrow_keys;var build;var refresh;var resize_thumbs;var that=CELL.cell(spec,my);pic=function(pic){if(!my.pics[pic.sha]){my.pics[pic.sha]=TL.pic_c($,{path:my.path+'/'+pic.sha,container:my.container,pic:pic});my.pics[pic.sha].build();}
return my.pics[pic.sha];};thumb=function(pic){if(!my.thumbs[pic.sha]){my.thumbs[pic.sha]=TL.pic_c($,{path:my.path+'/'+pic.sha+'_thumb',container:my.container,pic:pic});my.thumbs[pic.sha].build();}
return my.thumbs[pic.sha];};keep_index=function(len){if(my.index!=='undefined'&&my.index<len&&my.index>=0){my.element.find('.carousel-thumbs').css({'left':(-(my.thumbs_outer_width*my.index))+'px'});my.element.find('.carousel-thumbs .thumb').eq(my.index).addClass('hovered');}};resize_thumbs=function(plugin_width,plugin_height){var $thumbs=my.element.find('.carousel-thumbs');if(!(plugin_width>400&&plugin_height>300)){$thumbs.addClass('small');}
my.thumbs_width=$thumbs.hasClass('small')?20:my.thumbs_width;my.thumbs_outer_width=$thumbs.hasClass('small')?34:my.thumbs_outer_width;};handle_radius=function(pln){if(pln==='free'){my.element.css({'-webkit-border-radius':'4px 4px 0 0','-moz-border-radius':'4px 4px 0 0','border-radius':'4px 4px 0 0'});my.element.children().css({'-webkit-border-radius':'4px 4px 0 0','-moz-border-radius':'4px 4px 0 0','border-radius':'4px 4px 0 0'});}else{my.element.css({'-webkit-border-radius':'4px','-moz-border-radius':'4px','border-radius':'4px'});my.element.children().css({'-webkit-border-radius':'4px','-moz-border-radius':'4px','border-radius':'4px'});}};click_to_slide=function($element,width,len){$element.unbind('click');$element.click(function(e){var offsetX=(e.offsetX||e.pageX-$(e.target).offset().left);var offsetY=(e.offsetY||e.pageY-$(e.target).offset().top);if(offsetX<=width/5){$element.find('.carousel-thumbs .thumb').eq((my.shas.indexOf(my.current)-1)%len).trigger('click');}else{$element.find('.carousel-thumbs .thumb').eq((my.shas.indexOf(my.current)+1)%len).trigger('click');}});};bind_arrow_keys=function(len){my.element.click(function(e){e.stopImmediatePropagation();my.element.data('has_focus',true);});$('body').unbind('click.teleportd-plugin keyup.teleportd-plugin');$('body').bind('click.teleportd-plugin',function(){my.element.data('has_focus',false);});$('body').bind('keyup.teleportd-plugin',function(e){if(my.element.data('has_focus')){if(e.which===37){my.element.find('.carousel-thumbs .thumb').eq((my.shas.indexOf(my.current)-1)%len).trigger('click');}else if(e.which===39){my.element.find('.carousel-thumbs .thumb').eq((my.shas.indexOf(my.current)+1)%len).trigger('click');}}});};build=function(){my.element=$('<div/>').addClass('teleportd-plugin-carousel teleportd-layout');return my.element;};refresh=function(json){my.children={};my.shas=[];my.element.empty();my.element.append($('<div/>').addClass('carousel-thumbs'));my.element.find('.carousel-thumbs').empty();my.element.css('width',json.width+'px');my.element.css('height',json.height+'px');resize_thumbs(json.width,json.height);var w=parseInt(json.width/2,10)-parseInt(my.thumbs_outer_width/2,10);my.element.find('.carousel-thumbs').css('width',my.thumbs_outer_width*json.pics.length+'px');my.element.find('.carousel-thumbs').css('bottom','5px');my.element.find('.carousel-thumbs').css({'padding-left':w,'padding-right':w});for(var i=0;i<json.pics.length;i++){my.shas.push(json.pics[i].sha);}
for(var i=0;i<json.pics.length;i++){my.current=my.current||json.pics[0].sha;var p=pic(json.pics[i]);my.children[json.pics[i].sha]=p;var t=thumb(json.pics[i]);my.children[json.pics[i].sha+'_thumb']=t;my.element.append(p.element());my.element.find('.carousel-thumbs').append(t.element().addClass('thumb').click(function(e){e.stopImmediatePropagation();my.element.data('has_focus',true);my.current=$(this).attr('teleportd-data-sha');my.index=my.shas.indexOf(my.current);$(this).parent().children().removeClass('hovered');$(this).addClass('hovered');my.element.find('.carousel-thumbs').stop(true);my.element.find('.carousel-thumbs').animate({'left':(-(my.thumbs_outer_width*my.index))+'px' },600,'easeInOutQuint');for(var i=0;i<json.pics.length;i++){json[json.pics[i].sha]={plg:json.plg,css:{width:json.width,height:json.height,top:0,left:(i-my.index)*json.width},transition:{animate:(TL.isIE?'css':'js'),duration:'.6s',easing:'easeInOutQuint'}};}
_super.refresh(json);}));my.index=my.shas.indexOf(my.current)===-1?0:my.shas.indexOf(my.current);json[json.pics[i].sha]={plg:json.plg,css:{width:json.width,height:json.height,top:0,left:(i-my.index)*json.width},transition:{animate:false}};json[json.pics[i].sha+'_thumb']={plg:{layout:json.plg.layout,caption_display:false},css:{position:'relative',width:my.thumbs_width,height:my.thumbs_width,top:'none',left:'none'},transition:{animate:'css',duration:'.2s',easing:'linear'}};}
keep_index(json.pics.length);handle_radius(json.pln);click_to_slide(my.element,json.width,json.pics.length);click_to_slide(my.element.parent().find('.teleportd-glass'),json.width,json.pics.length);bind_arrow_keys(json.pics.length);_super.refresh(json);};CELL.method(that,'pic',pic,_super);CELL.method(that,'thumb',thumb,_super);CELL.method(that,'build',build,_super);CELL.method(that,'refresh',refresh,_super);return that;};var TL=TL||{waits:[]};TL.taquin_c=function($,spec,my){var _super={};my=my||{};my.pics={};my.PATTERN=[[],[],[1,1,1,1],[1,2,2,1],[1,2,2,3],[[4,4,4,4],[4,4,4,4],[4,4,4,4],[4,4,4,4]],[[4,4,4,4],[4,4,4,4],[5,5,5,5],[5,5,5,5]],[[4,4,4,4],[5,5,5,5],[6,6,6,6],[6,6,6,6]]
[[4,4,4,4],[5,5,5,5],[6,6,6,6],[7,7,7,7]],[[4,4,4,4],[5,8,8,5],[6,6,6,6],[7,8,8,7]],[[4,5,6,7],[8,9,4,5],[6,7,8,9],[4,5,6,7]],[[4,5,6,7],[8,9,10,4],[5,6,7,8],[9,10,4,5]],[[4,5,6,7],[8,9,10,11],[4,5,6,7],[8,9,10,11]],[[4,5,6,7],[8,9,10,11],[12,4,5,6],[7,8,9,10]],[[4,5,6,7],[8,9,10,11],[12,13,4,5],[6,7,8,9]],[[4,5,6,7],[8,9,10,11],[12,13,14,4],[5,6,7,8]],[[4,5,6,7],[8,9,10,11],[12,13,14,15],[4,5,6,7]],[[4,5,6,7],[8,9,10,11],[12,13,14,15],[16,4,5,6]],[[4,5,6,7],[8,9,10,11],[12,13,14,15],[16,17,4,5]],[[4,5,6,7],[8,9,10,11],[12,13,14,15],[16,17,18,4]],[[4,5,6,7],[8,9,10,11],[12,13,14,15],[16,17,18,19]]];var pic;var handle_radius;var build;var refresh;var that=CELL.cell(spec,my);pic=function(pic,pos){if(!my.pics[pic.sha+'_'+pos]){my.pics[pic.sha+'_'+pos]=TL.pic_c($,{path:my.path+'/'+pic.sha,container:my.container,pic:pic});my.pics[pic.sha+'_'+pos].build();}
return my.pics[pic.sha+'_'+pos];};handle_radius=function(json){var qrad,crad;if(json.pln==='free'){if(json.pics.length<5){qrad=['4px 4px 0 0','4px 4px 0 0','4px 4px 0 0','4px 4px 0 0'];crad=['4px 4px 0 0','4px 4px 0 0','4px 4px 0 0','4px 4px 0 0'];}else{qrad=['4px 0 0 0','0 4px 0 0','0','0'];crad=['4px 0 0 0','0 4px 0 0','0','0'];}
my.element.css({'-webkit-border-radius':'4px 4px 0 0','-moz-border-radius':'4px 4px 0 0','border-radius':'4px 4px 0 0'});for(var i=0;i<4;i++){my.element.find('.teleportd-taquin-container').eq(i).children().css({'-webkit-border-radius':qrad[i],'-moz-border-radius':qrad[i],'border-radius':qrad[i]});my.element.find('.teleportd-taquin-container').eq(i).find('.teleportd-plugin-caption').css({'-webkit-border-radius':crad[i],'-moz-border-radius':crad[i],'border-radius':crad[i]});}}else{if(json.pics.length<5){qrad=['4px','4px','4px','4px'];crad=['4px 4px 0 0','4px 4px 0 0','4px 4px 0 0','4px 4px 0 0'];}else{qrad=['4px 0 0 0','0 4px 0 0','0 0 4px 0','0 0 0 4px'];crad=['4px 0 0 0','0 4px 0 0','0','0'];}
my.element.css({'-webkit-border-radius':'4px','-moz-border-radius':'4px','border-radius':'4px'});for(var i=0;i<4;i++){my.element.find('.teleportd-taquin-container').eq(i).children().css({'-webkit-border-radius':qrad[i],'-moz-border-radius':qrad[i],'border-radius':qrad[i]});my.element.find('.teleportd-taquin-container').eq(i).find('.teleportd-plugin-caption').css({'-webkit-border-radius':crad[i],'-moz-border-radius':crad[i],'border-radius':crad[i]});}}};build=function(){my.element=$('<div/>').addClass('teleportd-plugin-taquin teleportd-layout');return my.element;};refresh=function(json){my.children={};my.shas=[];my.element.empty();my.element.css('width',json.width+'px');my.element.css('height',json.height+'px');var container_setup=function(pattern,ctpos,topidx,frame){var el=$('<div/>').addClass('teleportd-taquin-container').css(frame);var pidx=CELL.unique(pattern);var add_pic=function(idx,left){var p=pic(json.pics[idx],ctpos);my.children[json.pics[idx].sha+'_'+ctpos]=p;el.append(p.element());json[json.pics[idx].sha+'_'+ctpos]={plg:json.plg,css:{width:frame.width,height:frame.height,left:left},transition:{animate:false}};}
add_pic(topidx,0);for(var i=0;i<pidx.length;i++){add_pic(pidx[i],frame.width);}
if(pidx.length>0){el.hover(function(e){var offsetX=(e.offsetX||e.pageX-$(e.target).offset().left);var offsetY=(e.offsetY||e.pageY-$(e.target).offset().top);var pos={};if((offsetX/frame.width)>(offsetY/frame.height)&&(offsetX/frame.width)<(1-offsetY/frame.height)){pos={'mouse':0,'current':{'top':frame.height,'left':0},'next':{'top':-(frame.height),'left':0}};}else if((offsetX/frame.width)>(offsetY/frame.height)&&(offsetX/frame.width)>(1-offsetY/frame.height)){pos={'mouse':1,'current':{'top':0,'left':-(frame.width)},'next':{'top':0,'left':frame.width}};}else if((offsetX/frame.width)<(offsetY/frame.height)&&(offsetX/frame.width)>(1-offsetY/frame.height)){pos={'mouse':2,'current':{'top':-(frame.height),'left':0},'next':{'top':frame.height,'left':0}};}else if((offsetX/frame.width)<(offsetY/frame.height)&&(offsetX/frame.width)<(1-offsetY/frame.height)){pos={'mouse':3,'current':{'top':0,'left':frame.width},'next':{'top':0,'left':-(frame.width)}};}
if(pos!=='undefined'){var current,next;if(e['type']==='mouseenter'){current=topidx;next=pattern[pos.mouse];el.attr('teleportd-original-pic',pattern[pos.mouse]);}
if(e['type']==='mouseleave'){pos={'mouse':pos.mouse,'current':{'top':-(pos.current.top),'left':-(pos.current.left)},'next':{'top':-(pos.next.top),'left':-(pos.next.left)}};current=parseInt(el.attr('teleportd-original-pic'),10);next=topidx;}
json[json.pics[next].sha+'_'+ctpos]={plg:json.plg,css:{width:frame.width,height:frame.height,top:pos.next.top,left:pos.next.left},transition:{animate:false}};my.children[json.pics[next].sha+'_'+ctpos].refresh(json[json.pics[next].sha+'_'+ctpos]);setTimeout(function(){json[json.pics[current].sha+'_'+ctpos]={plg:json.plg,css:{width:frame.width,height:frame.height,top:pos.current.top,left:pos.current.left},transition:{animate:'css',duration:'.15s',easing:'linear'}};my.children[json.pics[current].sha+'_'+ctpos].refresh(json[json.pics[current].sha+'_'+ctpos]);json[json.pics[next].sha+'_'+ctpos]={plg:json.plg,css:{width:frame.width,height:frame.height,top:0,left:0},transition:{animate:'css',duration:'.15s',easing:'linear'}};my.children[json.pics[next].sha+'_'+ctpos].refresh(json[json.pics[next].sha+'_'+ctpos]);},20);}});}
return el;};if(json.pics.length>0&&json.pics.length<5){my.element.append(container_setup(my.PATTERN[json.pics.length],'NONE',0,{width:json.width,height:json.height,top:0,left:0}));}
if(json.pics.length>=5){var frames=[{'top':0,'left':0,'width':json.width/2,'height':json.height/2},{'top':0,'left':json.width/2,'width':json.width/2,'height':json.height/2},{'top':json.height/2,'left':json.width/2,'width':json.width/2,'height':json.height/2},{'top':json.height/2,'left':0,'width':json.width/2,'height':json.height/2}];for(var i=0;i<frames.length;i++){var ctpos=['NW','NE','SE','SW'];my.element.append(container_setup(my.PATTERN[Math.min(json.pics.length,my.PATTERN.length-1)][i],ctpos[i],i,frames[i]));}}
handle_radius(json);_super.refresh(json);};CELL.method(that,'pic',pic,_super);CELL.method(that,'handle_radius',handle_radius,_super);CELL.method(that,'build',build,_super);CELL.method(that,'refresh',refresh,_super);return that;};var TL=TL||{waits:[]};TL.pic_c=function($,spec,my){var _super={};my=my||{};my.pic=spec.pic;var build;var refresh;var resize_caption;var that=CELL.cell(spec,my);resize_caption=function(pic_width,pic_height){if(!(pic_width>400&&pic_height>300)){my.element.find('.teleportd-plugin-caption').addClass('small');}};build=function(){my.element=$('<div/>').attr('teleportd-data-sha',my.pic.sha).append($('<div/>').addClass('teleportd-plugin-caption hidden').append($('<a/>').addClass('teleportd-profile-pic').attr('target','_blank')).append($('<div/>').addClass('teleportd-caption-info').append($('<div/>').addClass('teleportd-caption-handle hidden')).append($('<div/>').addClass('teleportd-caption-date hidden')).append($('<div/>').addClass('teleportd-caption-platform hidden'))));my.img=new Image();my.img.src=my.pic.fll;my.img.onload=function(){my.img_width=this.width;my.img_height=this.height;};return my.element;};refresh=function(json){var fit=function(){if(my.img_width*json.css.height>my.img_height*json.css.width){my.element.css('background-size','auto 100%');}else{my.element.css('background-size','100% auto');}};var relative_date=function(timestamp){var SECOND=1000,MINUTE=60*SECOND,HOUR=60*MINUTE,DAY=24*HOUR,WEEK=7*DAY,YEAR=DAY*365,MONTH=YEAR/12;var formats=[[0.7*MINUTE,'just now'],[1.5*MINUTE,'a minute ago'],[60*MINUTE,'minutes ago',MINUTE],[1.5*HOUR,'an hour ago'],[DAY,'hours ago',HOUR],[1.5*DAY,'yesterday'],[7*DAY,'days ago',DAY],[1.5*WEEK,'a week ago'],[MONTH,'weeks ago',WEEK],[1.5*MONTH,'a month ago'],[YEAR,'months ago',MONTH],[1.5*YEAR,'a year ago'],[Number.MAX_VALUE,'years ago',YEAR]];var delta=(new Date).getTime()-timestamp,len=formats.length,format;for(i=0;i<len;i++){format=formats[i];if(delta<format[0]){return format[2]===undefined?format[1]:Math.round(delta/format[2])+' '+format[1];}}};my.element.css('background-image','url('+my.pic.fll+')');if(json.transition.animate==='js'){my.element.stop();my.element.animate(json.css,parseInt(parseFloat(json.transition.duration,10)*1000,10),json.transition.easing);}else{if(json.transition.animate==='css'){my.element.css({'-webkit-transition-duration':json.transition.duration,'-moz-transition-duration':json.transition.duration,'transition-duration':json.transition.duration});}else{my.element.css({'-webkit-transition-duration':'0s','-moz-transition-duration':'0s','transition-duration':'0s'});}
setTimeout(function(){my.element.css(json.css);},10);}
my.element.find('.teleportd-profile-pic').attr('href',my.pic.lnk).css('background-image','url('+my.pic.pic+')');my.element.find('.teleportd-caption-handle').html('<a href="'+my.pic.lnk+'" target="_blank">@'+my.pic.hdl+'</a>');my.element.find('.teleportd-caption-date').html(relative_date(my.pic.dte)).attr('title',new Date(my.pic.dte).toDateString());my.element.find('.teleportd-caption-platform').addClass(my.pic.src);$('.teleportd-plugin-caption').hover(function(){var $this=$(this);$this.find('.teleportd-caption-handle').removeClass('hidden').addClass('visible');setTimeout(function(){$this.find('.teleportd-caption-date').removeClass('hidden').addClass('visible');},100);setTimeout(function(){$this.find('.teleportd-caption-platform').removeClass('hidden').addClass('visible');},200);},function(){var $this=$(this);$this.find('.teleportd-caption-handle').removeClass('visible').addClass('hidden');setTimeout(function(){$this.find('.teleportd-caption-date').removeClass('visible').addClass('hidden');},100);setTimeout(function(){$this.find('.teleportd-caption-platform').removeClass('visible').addClass('hidden');},200);}).click(function(e){e.stopImmediatePropagation();});if(json.plg.caption_display){my.element.find('.teleportd-plugin-caption').removeClass('hidden').addClass('visible');}else{my.element.find('.teleportd-plugin-caption').removeClass('visible').addClass('hidden');}
if(typeof my.img_width!=='undefined'&&typeof my.img_height!=='undefined'){fit();}else{my.img.onload=function(){my.img_width=this.width;my.img_height=this.height;fit();};}
resize_caption(json.css.width,json.css.height);_super.refresh();};CELL.method(that,'build',build,_super);CELL.method(that,'refresh',refresh,_super);return that;};